permalink: /:title

plugins::
  - jekyll-sitemap

safe: true
lsi: false
hightlighter: rouge

name: Rascal - Meta Programming Language
title: Rascal - Meta Programming Language

production_url: http://usethesource.io/blog/

exclude: ["README.md"]

blogname: RascalMPL Blog 
description: Rascal's blog.
url: http://www.rascal-mpl.org/ 
